=== JarSeal/threejs-rapier/.schemas/texture.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "fileName": {
      "type": "string"
    },
    "path": {
      "type": "string"
    },
    "useHDRLoader": {
      "type": "boolean"
    },
    "texOpts": {
      "type": "object",
      "properties": {
        "image": {},
        "mapping": {
          "type": "number"
        },
        "wrapS": {
          "type": "number"
        },
        "wrapT": {
          "type": "number"
        },
        "magFilter": {
          "type": "number"
        },
        "minFilter": {
          "type": "number"
        },
        "type": {
          "type": "number"
        },
        "anisotropy": {
          "type": "number"
        },
        "colorSpace": {
          "anyOf": [
            {
              "type": "string",
              "const": ""
            },
            {
              "type": "string",
              "const": "srgb"
            },
            {
              "type": "string",
              "const": "srgb-linear"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "throwOnError": {
      "type": "boolean"
    },
    "userData": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {}
    },
    "debugData": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "comments": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "timestamp": {
                "type": "number"
              },
              "comment": {
                "type": "string"
              }
            },
            "required": [
              "timestamp",
              "comment"
            ],
            "additionalProperties": false
          }
        },
        "todo": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {}
        },
        "debugObj": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {}
        }
      },
      "additionalProperties": false
    },
    "__saveData": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "__meta": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "number"
                },
                "engineVersion": {
                  "type": "string",
                  "pattern": "^\\d+\\.\\d+\\.\\d+$"
                },
                "toolkitVersion": {
                  "type": "string",
                  "pattern": "^\\d+\\.\\d+\\.\\d+$"
                },
                "appVersion": {
                  "type": "string",
                  "pattern": "^\\d+\\.\\d+\\.\\d+$"
                }
              },
              "additionalProperties": false
            },
            "id": {
              "type": "string"
            },
            "fileName": {
              "type": "string"
            },
            "path": {
              "type": "string"
            },
            "useHDRLoader": {
              "type": "boolean"
            },
            "texOpts": {
              "type": "object",
              "properties": {
                "image": {},
                "mapping": {
                  "type": "number"
                },
                "wrapS": {
                  "type": "number"
                },
                "wrapT": {
                  "type": "number"
                },
                "magFilter": {
                  "type": "number"
                },
                "minFilter": {
                  "type": "number"
                },
                "type": {
                  "type": "number"
                },
                "anisotropy": {
                  "type": "number"
                },
                "colorSpace": {
                  "anyOf": [
                    {
                      "type": "string",
                      "const": ""
                    },
                    {
                      "type": "string",
                      "const": "srgb"
                    },
                    {
                      "type": "string",
                      "const": "srgb-linear"
                    }
                  ]
                }
              },
              "additionalProperties": false
            },
            "throwOnError": {
              "type": "boolean"
            },
            "userData": {
              "type": "object",
              "propertyNames": {
                "type": "string"
              },
              "additionalProperties": {}
            },
            "debugData": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "comments": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "timestamp": {
                        "type": "number"
                      },
                      "comment": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "timestamp",
                      "comment"
                    ],
                    "additionalProperties": false
                  }
                },
                "todo": {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                },
                "debugObj": {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        }
      }
    },
    "__sourcePath": {
      "type": "string"
    },
    "__fileSize": {
      "type": "number"
    }
  },
  "additionalProperties": false
}

=== JarSeal/threejs-rapier/src/app/textures/testTexture.texture.json
{
  "$schema": "../../../.schemas/texture.schema.json",
  "id": "testTexture",
  "fileName": "/debugger/assets/testTextures/Poliigon_MetalRust_7642_BaseColor.jpg",
  "useHDRLoader": false,
  "__saveData": {
    "sceneTestECS": [
      {
        "__meta": { "date": 1779449688109 },
        "useHDRLoader": true
      }
    ]
  }
}
